FROM node:20-alpine

WORKDIR /app

# Install dependencies
COPY evaeval/dashboard_frontend/package*.json ./
RUN npm install

# Copy application source
COPY evaeval/dashboard_frontend ./

EXPOSE 3000

ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

CMD ["npm", "run", "dev"]
